// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SessionDeviceRole } from '../../sprint-sync/schema/session-device-role.js';


export class DeviceTelemetry {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DeviceTelemetry {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDeviceTelemetry(bb:flatbuffers.ByteBuffer, obj?:DeviceTelemetry):DeviceTelemetry {
  return (obj || new DeviceTelemetry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDeviceTelemetry(bb:flatbuffers.ByteBuffer, obj?:DeviceTelemetry):DeviceTelemetry {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DeviceTelemetry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

stableDeviceId():string|null
stableDeviceId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
stableDeviceId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

role():SessionDeviceRole {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : SessionDeviceRole.UNASSIGNED;
}

sensitivity():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

latencyMs():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : -1;
}

clockSynced():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

analysisWidth():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : -1;
}

analysisHeight():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : -1;
}

timestampMillis():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startDeviceTelemetry(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addStableDeviceId(builder:flatbuffers.Builder, stableDeviceIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, stableDeviceIdOffset, 0);
}

static addRole(builder:flatbuffers.Builder, role:SessionDeviceRole) {
  builder.addFieldInt8(1, role, SessionDeviceRole.UNASSIGNED);
}

static addSensitivity(builder:flatbuffers.Builder, sensitivity:number) {
  builder.addFieldInt32(2, sensitivity, 0);
}

static addLatencyMs(builder:flatbuffers.Builder, latencyMs:number) {
  builder.addFieldInt32(3, latencyMs, -1);
}

static addClockSynced(builder:flatbuffers.Builder, clockSynced:boolean) {
  builder.addFieldInt8(4, +clockSynced, +false);
}

static addAnalysisWidth(builder:flatbuffers.Builder, analysisWidth:number) {
  builder.addFieldInt32(5, analysisWidth, -1);
}

static addAnalysisHeight(builder:flatbuffers.Builder, analysisHeight:number) {
  builder.addFieldInt32(6, analysisHeight, -1);
}

static addTimestampMillis(builder:flatbuffers.Builder, timestampMillis:bigint) {
  builder.addFieldInt64(7, timestampMillis, BigInt('0'));
}

static endDeviceTelemetry(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDeviceTelemetry(builder:flatbuffers.Builder, stableDeviceIdOffset:flatbuffers.Offset, role:SessionDeviceRole, sensitivity:number, latencyMs:number, clockSynced:boolean, analysisWidth:number, analysisHeight:number, timestampMillis:bigint):flatbuffers.Offset {
  DeviceTelemetry.startDeviceTelemetry(builder);
  DeviceTelemetry.addStableDeviceId(builder, stableDeviceIdOffset);
  DeviceTelemetry.addRole(builder, role);
  DeviceTelemetry.addSensitivity(builder, sensitivity);
  DeviceTelemetry.addLatencyMs(builder, latencyMs);
  DeviceTelemetry.addClockSynced(builder, clockSynced);
  DeviceTelemetry.addAnalysisWidth(builder, analysisWidth);
  DeviceTelemetry.addAnalysisHeight(builder, analysisHeight);
  DeviceTelemetry.addTimestampMillis(builder, timestampMillis);
  return DeviceTelemetry.endDeviceTelemetry(builder);
}
}
