// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum SessionDeviceRole {
  UNASSIGNED = 0,
  START = 1,
  SPLIT1 = 2,
  SPLIT2 = 3,
  SPLIT3 = 4,
  SPLIT4 = 5,
  STOP = 6,
  DISPLAY = 7
}
