// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SessionTrigger {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SessionTrigger {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSessionTrigger(bb:flatbuffers.ByteBuffer, obj?:SessionTrigger):SessionTrigger {
  return (obj || new SessionTrigger()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSessionTrigger(bb:flatbuffers.ByteBuffer, obj?:SessionTrigger):SessionTrigger {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SessionTrigger()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

triggerType():string|null
triggerType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
triggerType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

splitIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : -1;
}

triggerSensorNanos():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startSessionTrigger(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addTriggerType(builder:flatbuffers.Builder, triggerTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, triggerTypeOffset, 0);
}

static addSplitIndex(builder:flatbuffers.Builder, splitIndex:number) {
  builder.addFieldInt32(1, splitIndex, -1);
}

static addTriggerSensorNanos(builder:flatbuffers.Builder, triggerSensorNanos:bigint) {
  builder.addFieldInt64(2, triggerSensorNanos, BigInt('0'));
}

static endSessionTrigger(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // triggerType
  return offset;
}

static createSessionTrigger(builder:flatbuffers.Builder, triggerTypeOffset:flatbuffers.Offset, splitIndex:number, triggerSensorNanos:bigint):flatbuffers.Offset {
  SessionTrigger.startSessionTrigger(builder);
  SessionTrigger.addTriggerType(builder, triggerTypeOffset);
  SessionTrigger.addSplitIndex(builder, splitIndex);
  SessionTrigger.addTriggerSensorNanos(builder, triggerSensorNanos);
  return SessionTrigger.endSessionTrigger(builder);
}
}
