// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ClockResyncRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ClockResyncRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsClockResyncRequest(bb:flatbuffers.ByteBuffer, obj?:ClockResyncRequest):ClockResyncRequest {
  return (obj || new ClockResyncRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsClockResyncRequest(bb:flatbuffers.ByteBuffer, obj?:ClockResyncRequest):ClockResyncRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ClockResyncRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sampleCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startClockResyncRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addSampleCount(builder:flatbuffers.Builder, sampleCount:number) {
  builder.addFieldInt32(0, sampleCount, 0);
}

static endClockResyncRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createClockResyncRequest(builder:flatbuffers.Builder, sampleCount:number):flatbuffers.Offset {
  ClockResyncRequest.startClockResyncRequest(builder);
  ClockResyncRequest.addSampleCount(builder, sampleCount);
  return ClockResyncRequest.endClockResyncRequest(builder);
}
}
