// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class DeviceIdentity {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DeviceIdentity {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDeviceIdentity(bb:flatbuffers.ByteBuffer, obj?:DeviceIdentity):DeviceIdentity {
  return (obj || new DeviceIdentity()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDeviceIdentity(bb:flatbuffers.ByteBuffer, obj?:DeviceIdentity):DeviceIdentity {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DeviceIdentity()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

stableDeviceId():string|null
stableDeviceId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
stableDeviceId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

deviceName():string|null
deviceName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
deviceName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startDeviceIdentity(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addStableDeviceId(builder:flatbuffers.Builder, stableDeviceIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, stableDeviceIdOffset, 0);
}

static addDeviceName(builder:flatbuffers.Builder, deviceNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, deviceNameOffset, 0);
}

static endDeviceIdentity(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDeviceIdentity(builder:flatbuffers.Builder, stableDeviceIdOffset:flatbuffers.Offset, deviceNameOffset:flatbuffers.Offset):flatbuffers.Offset {
  DeviceIdentity.startDeviceIdentity(builder);
  DeviceIdentity.addStableDeviceId(builder, stableDeviceIdOffset);
  DeviceIdentity.addDeviceName(builder, deviceNameOffset);
  return DeviceIdentity.endDeviceIdentity(builder);
}
}
