// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SessionDeviceRole } from '../../sprint-sync/schema/session-device-role.js';


export class SessionSplitMark {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SessionSplitMark {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSessionSplitMark(bb:flatbuffers.ByteBuffer, obj?:SessionSplitMark):SessionSplitMark {
  return (obj || new SessionSplitMark()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSessionSplitMark(bb:flatbuffers.ByteBuffer, obj?:SessionSplitMark):SessionSplitMark {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SessionSplitMark()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

role():SessionDeviceRole {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : SessionDeviceRole.UNASSIGNED;
}

hostSensorNanos():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startSessionSplitMark(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addRole(builder:flatbuffers.Builder, role:SessionDeviceRole) {
  builder.addFieldInt8(0, role, SessionDeviceRole.UNASSIGNED);
}

static addHostSensorNanos(builder:flatbuffers.Builder, hostSensorNanos:bigint) {
  builder.addFieldInt64(1, hostSensorNanos, BigInt('0'));
}

static endSessionSplitMark(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSessionSplitMark(builder:flatbuffers.Builder, role:SessionDeviceRole, hostSensorNanos:bigint):flatbuffers.Offset {
  SessionSplitMark.startSessionSplitMark(builder);
  SessionSplitMark.addRole(builder, role);
  SessionSplitMark.addHostSensorNanos(builder, hostSensorNanos);
  return SessionSplitMark.endSessionSplitMark(builder);
}
}
