// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SessionSnapshotDevice } from '../../sprint-sync/schema/session-snapshot-device.js';
import { SessionSplitMark } from '../../sprint-sync/schema/session-split-mark.js';


export class SessionSnapshot {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SessionSnapshot {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSessionSnapshot(bb:flatbuffers.ByteBuffer, obj?:SessionSnapshot):SessionSnapshot {
  return (obj || new SessionSnapshot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSessionSnapshot(bb:flatbuffers.ByteBuffer, obj?:SessionSnapshot):SessionSnapshot {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SessionSnapshot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

stage():string|null
stage(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
stage(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

monitoringActive():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

devices(index: number, obj?:SessionSnapshotDevice):SessionSnapshotDevice|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new SessionSnapshotDevice()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

devicesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

hostStartSensorNanos():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('-1');
}

hostStopSensorNanos():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('-1');
}

hostSplitMarks(index: number, obj?:SessionSplitMark):SessionSplitMark|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new SessionSplitMark()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

hostSplitMarksLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

runId():string|null
runId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
runId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

hostSensorMinusElapsedNanos():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('-1');
}

hostGpsUtcOffsetNanos():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('-1');
}

hostGpsFixAgeNanos():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('-1');
}

selfDeviceId():string|null
selfDeviceId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
selfDeviceId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

anchorDeviceId():string|null
anchorDeviceId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
anchorDeviceId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

anchorState():string|null
anchorState(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
anchorState(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startSessionSnapshot(builder:flatbuffers.Builder) {
  builder.startObject(13);
}

static addStage(builder:flatbuffers.Builder, stageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, stageOffset, 0);
}

static addMonitoringActive(builder:flatbuffers.Builder, monitoringActive:boolean) {
  builder.addFieldInt8(1, +monitoringActive, +false);
}

static addDevices(builder:flatbuffers.Builder, devicesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, devicesOffset, 0);
}

static createDevicesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDevicesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addHostStartSensorNanos(builder:flatbuffers.Builder, hostStartSensorNanos:bigint) {
  builder.addFieldInt64(3, hostStartSensorNanos, BigInt('-1'));
}

static addHostStopSensorNanos(builder:flatbuffers.Builder, hostStopSensorNanos:bigint) {
  builder.addFieldInt64(4, hostStopSensorNanos, BigInt('-1'));
}

static addHostSplitMarks(builder:flatbuffers.Builder, hostSplitMarksOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, hostSplitMarksOffset, 0);
}

static createHostSplitMarksVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startHostSplitMarksVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRunId(builder:flatbuffers.Builder, runIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, runIdOffset, 0);
}

static addHostSensorMinusElapsedNanos(builder:flatbuffers.Builder, hostSensorMinusElapsedNanos:bigint) {
  builder.addFieldInt64(7, hostSensorMinusElapsedNanos, BigInt('-1'));
}

static addHostGpsUtcOffsetNanos(builder:flatbuffers.Builder, hostGpsUtcOffsetNanos:bigint) {
  builder.addFieldInt64(8, hostGpsUtcOffsetNanos, BigInt('-1'));
}

static addHostGpsFixAgeNanos(builder:flatbuffers.Builder, hostGpsFixAgeNanos:bigint) {
  builder.addFieldInt64(9, hostGpsFixAgeNanos, BigInt('-1'));
}

static addSelfDeviceId(builder:flatbuffers.Builder, selfDeviceIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, selfDeviceIdOffset, 0);
}

static addAnchorDeviceId(builder:flatbuffers.Builder, anchorDeviceIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(11, anchorDeviceIdOffset, 0);
}

static addAnchorState(builder:flatbuffers.Builder, anchorStateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(12, anchorStateOffset, 0);
}

static endSessionSnapshot(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSessionSnapshot(builder:flatbuffers.Builder, stageOffset:flatbuffers.Offset, monitoringActive:boolean, devicesOffset:flatbuffers.Offset, hostStartSensorNanos:bigint, hostStopSensorNanos:bigint, hostSplitMarksOffset:flatbuffers.Offset, runIdOffset:flatbuffers.Offset, hostSensorMinusElapsedNanos:bigint, hostGpsUtcOffsetNanos:bigint, hostGpsFixAgeNanos:bigint, selfDeviceIdOffset:flatbuffers.Offset, anchorDeviceIdOffset:flatbuffers.Offset, anchorStateOffset:flatbuffers.Offset):flatbuffers.Offset {
  SessionSnapshot.startSessionSnapshot(builder);
  SessionSnapshot.addStage(builder, stageOffset);
  SessionSnapshot.addMonitoringActive(builder, monitoringActive);
  SessionSnapshot.addDevices(builder, devicesOffset);
  SessionSnapshot.addHostStartSensorNanos(builder, hostStartSensorNanos);
  SessionSnapshot.addHostStopSensorNanos(builder, hostStopSensorNanos);
  SessionSnapshot.addHostSplitMarks(builder, hostSplitMarksOffset);
  SessionSnapshot.addRunId(builder, runIdOffset);
  SessionSnapshot.addHostSensorMinusElapsedNanos(builder, hostSensorMinusElapsedNanos);
  SessionSnapshot.addHostGpsUtcOffsetNanos(builder, hostGpsUtcOffsetNanos);
  SessionSnapshot.addHostGpsFixAgeNanos(builder, hostGpsFixAgeNanos);
  SessionSnapshot.addSelfDeviceId(builder, selfDeviceIdOffset);
  SessionSnapshot.addAnchorDeviceId(builder, anchorDeviceIdOffset);
  SessionSnapshot.addAnchorState(builder, anchorStateOffset);
  return SessionSnapshot.endSessionSnapshot(builder);
}
}
