// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SessionDeviceRole } from '../../sprint-sync/schema/session-device-role.js';


export class SessionTriggerRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SessionTriggerRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSessionTriggerRequest(bb:flatbuffers.ByteBuffer, obj?:SessionTriggerRequest):SessionTriggerRequest {
  return (obj || new SessionTriggerRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSessionTriggerRequest(bb:flatbuffers.ByteBuffer, obj?:SessionTriggerRequest):SessionTriggerRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SessionTriggerRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

role():SessionDeviceRole {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : SessionDeviceRole.UNASSIGNED;
}

triggerSensorNanos():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

mappedHostSensorNanos():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('-1');
}

sourceDeviceId():string|null
sourceDeviceId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sourceDeviceId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

sourceElapsedNanos():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

mappedAnchorElapsedNanos():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('-1');
}

static startSessionTriggerRequest(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addRole(builder:flatbuffers.Builder, role:SessionDeviceRole) {
  builder.addFieldInt8(0, role, SessionDeviceRole.UNASSIGNED);
}

static addTriggerSensorNanos(builder:flatbuffers.Builder, triggerSensorNanos:bigint) {
  builder.addFieldInt64(1, triggerSensorNanos, BigInt('0'));
}

static addMappedHostSensorNanos(builder:flatbuffers.Builder, mappedHostSensorNanos:bigint) {
  builder.addFieldInt64(2, mappedHostSensorNanos, BigInt('-1'));
}

static addSourceDeviceId(builder:flatbuffers.Builder, sourceDeviceIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, sourceDeviceIdOffset, 0);
}

static addSourceElapsedNanos(builder:flatbuffers.Builder, sourceElapsedNanos:bigint) {
  builder.addFieldInt64(4, sourceElapsedNanos, BigInt('0'));
}

static addMappedAnchorElapsedNanos(builder:flatbuffers.Builder, mappedAnchorElapsedNanos:bigint) {
  builder.addFieldInt64(5, mappedAnchorElapsedNanos, BigInt('-1'));
}

static endSessionTriggerRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 10) // sourceDeviceId
  return offset;
}

static createSessionTriggerRequest(builder:flatbuffers.Builder, role:SessionDeviceRole, triggerSensorNanos:bigint, mappedHostSensorNanos:bigint, sourceDeviceIdOffset:flatbuffers.Offset, sourceElapsedNanos:bigint, mappedAnchorElapsedNanos:bigint):flatbuffers.Offset {
  SessionTriggerRequest.startSessionTriggerRequest(builder);
  SessionTriggerRequest.addRole(builder, role);
  SessionTriggerRequest.addTriggerSensorNanos(builder, triggerSensorNanos);
  SessionTriggerRequest.addMappedHostSensorNanos(builder, mappedHostSensorNanos);
  SessionTriggerRequest.addSourceDeviceId(builder, sourceDeviceIdOffset);
  SessionTriggerRequest.addSourceElapsedNanos(builder, sourceElapsedNanos);
  SessionTriggerRequest.addMappedAnchorElapsedNanos(builder, mappedAnchorElapsedNanos);
  return SessionTriggerRequest.endSessionTriggerRequest(builder);
}
}
