// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SessionSplitMark } from '../../sprint-sync/schema/session-split-mark.js';


export class SessionTimelineSnapshot {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SessionTimelineSnapshot {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSessionTimelineSnapshot(bb:flatbuffers.ByteBuffer, obj?:SessionTimelineSnapshot):SessionTimelineSnapshot {
  return (obj || new SessionTimelineSnapshot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSessionTimelineSnapshot(bb:flatbuffers.ByteBuffer, obj?:SessionTimelineSnapshot):SessionTimelineSnapshot {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SessionTimelineSnapshot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

hostStartSensorNanos():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('-1');
}

hostStopSensorNanos():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('-1');
}

hostSplitMarks(index: number, obj?:SessionSplitMark):SessionSplitMark|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new SessionSplitMark()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

hostSplitMarksLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

sentElapsedNanos():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startSessionTimelineSnapshot(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addHostStartSensorNanos(builder:flatbuffers.Builder, hostStartSensorNanos:bigint) {
  builder.addFieldInt64(0, hostStartSensorNanos, BigInt('-1'));
}

static addHostStopSensorNanos(builder:flatbuffers.Builder, hostStopSensorNanos:bigint) {
  builder.addFieldInt64(1, hostStopSensorNanos, BigInt('-1'));
}

static addHostSplitMarks(builder:flatbuffers.Builder, hostSplitMarksOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, hostSplitMarksOffset, 0);
}

static createHostSplitMarksVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startHostSplitMarksVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addSentElapsedNanos(builder:flatbuffers.Builder, sentElapsedNanos:bigint) {
  builder.addFieldInt64(3, sentElapsedNanos, BigInt('0'));
}

static endSessionTimelineSnapshot(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSessionTimelineSnapshot(builder:flatbuffers.Builder, hostStartSensorNanos:bigint, hostStopSensorNanos:bigint, hostSplitMarksOffset:flatbuffers.Offset, sentElapsedNanos:bigint):flatbuffers.Offset {
  SessionTimelineSnapshot.startSessionTimelineSnapshot(builder);
  SessionTimelineSnapshot.addHostStartSensorNanos(builder, hostStartSensorNanos);
  SessionTimelineSnapshot.addHostStopSensorNanos(builder, hostStopSensorNanos);
  SessionTimelineSnapshot.addHostSplitMarks(builder, hostSplitMarksOffset);
  SessionTimelineSnapshot.addSentElapsedNanos(builder, sentElapsedNanos);
  return SessionTimelineSnapshot.endSessionTimelineSnapshot(builder);
}
}
