// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ClockResyncRequest } from '../../sprint-sync/schema/clock-resync-request.js';
import { DeviceConfigUpdate } from '../../sprint-sync/schema/device-config-update.js';
import { DeviceIdentity } from '../../sprint-sync/schema/device-identity.js';
import { DeviceTelemetry } from '../../sprint-sync/schema/device-telemetry.js';
import { LapResult } from '../../sprint-sync/schema/lap-result.js';
import { SessionSnapshot } from '../../sprint-sync/schema/session-snapshot.js';
import { SessionTimelineSnapshot } from '../../sprint-sync/schema/session-timeline-snapshot.js';
import { SessionTrigger } from '../../sprint-sync/schema/session-trigger.js';
import { SessionTriggerRequest } from '../../sprint-sync/schema/session-trigger-request.js';
import { TriggerRefinement } from '../../sprint-sync/schema/trigger-refinement.js';


export enum TelemetryPayload {
  NONE = 0,
  SessionTriggerRequest = 1,
  SessionTrigger = 2,
  SessionTimelineSnapshot = 3,
  SessionSnapshot = 4,
  TriggerRefinement = 5,
  DeviceConfigUpdate = 6,
  ClockResyncRequest = 7,
  DeviceIdentity = 8,
  DeviceTelemetry = 9,
  LapResult = 10
}

export function unionToTelemetryPayload(
  type: TelemetryPayload,
  accessor: (obj:ClockResyncRequest|DeviceConfigUpdate|DeviceIdentity|DeviceTelemetry|LapResult|SessionSnapshot|SessionTimelineSnapshot|SessionTrigger|SessionTriggerRequest|TriggerRefinement) => ClockResyncRequest|DeviceConfigUpdate|DeviceIdentity|DeviceTelemetry|LapResult|SessionSnapshot|SessionTimelineSnapshot|SessionTrigger|SessionTriggerRequest|TriggerRefinement|null
): ClockResyncRequest|DeviceConfigUpdate|DeviceIdentity|DeviceTelemetry|LapResult|SessionSnapshot|SessionTimelineSnapshot|SessionTrigger|SessionTriggerRequest|TriggerRefinement|null {
  switch(TelemetryPayload[type]) {
    case 'NONE': return null; 
    case 'SessionTriggerRequest': return accessor(new SessionTriggerRequest())! as SessionTriggerRequest;
    case 'SessionTrigger': return accessor(new SessionTrigger())! as SessionTrigger;
    case 'SessionTimelineSnapshot': return accessor(new SessionTimelineSnapshot())! as SessionTimelineSnapshot;
    case 'SessionSnapshot': return accessor(new SessionSnapshot())! as SessionSnapshot;
    case 'TriggerRefinement': return accessor(new TriggerRefinement())! as TriggerRefinement;
    case 'DeviceConfigUpdate': return accessor(new DeviceConfigUpdate())! as DeviceConfigUpdate;
    case 'ClockResyncRequest': return accessor(new ClockResyncRequest())! as ClockResyncRequest;
    case 'DeviceIdentity': return accessor(new DeviceIdentity())! as DeviceIdentity;
    case 'DeviceTelemetry': return accessor(new DeviceTelemetry())! as DeviceTelemetry;
    case 'LapResult': return accessor(new LapResult())! as LapResult;
    default: return null;
  }
}

export function unionListToTelemetryPayload(
  type: TelemetryPayload, 
  accessor: (index: number, obj:ClockResyncRequest|DeviceConfigUpdate|DeviceIdentity|DeviceTelemetry|LapResult|SessionSnapshot|SessionTimelineSnapshot|SessionTrigger|SessionTriggerRequest|TriggerRefinement) => ClockResyncRequest|DeviceConfigUpdate|DeviceIdentity|DeviceTelemetry|LapResult|SessionSnapshot|SessionTimelineSnapshot|SessionTrigger|SessionTriggerRequest|TriggerRefinement|null, 
  index: number
): ClockResyncRequest|DeviceConfigUpdate|DeviceIdentity|DeviceTelemetry|LapResult|SessionSnapshot|SessionTimelineSnapshot|SessionTrigger|SessionTriggerRequest|TriggerRefinement|null {
  switch(TelemetryPayload[type]) {
    case 'NONE': return null; 
    case 'SessionTriggerRequest': return accessor(index, new SessionTriggerRequest())! as SessionTriggerRequest;
    case 'SessionTrigger': return accessor(index, new SessionTrigger())! as SessionTrigger;
    case 'SessionTimelineSnapshot': return accessor(index, new SessionTimelineSnapshot())! as SessionTimelineSnapshot;
    case 'SessionSnapshot': return accessor(index, new SessionSnapshot())! as SessionSnapshot;
    case 'TriggerRefinement': return accessor(index, new TriggerRefinement())! as TriggerRefinement;
    case 'DeviceConfigUpdate': return accessor(index, new DeviceConfigUpdate())! as DeviceConfigUpdate;
    case 'ClockResyncRequest': return accessor(index, new ClockResyncRequest())! as ClockResyncRequest;
    case 'DeviceIdentity': return accessor(index, new DeviceIdentity())! as DeviceIdentity;
    case 'DeviceTelemetry': return accessor(index, new DeviceTelemetry())! as DeviceTelemetry;
    case 'LapResult': return accessor(index, new LapResult())! as LapResult;
    default: return null;
  }
}
