// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SessionDeviceRole } from '../../sprint-sync/schema/session-device-role.js';


export class TriggerRefinement {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TriggerRefinement {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTriggerRefinement(bb:flatbuffers.ByteBuffer, obj?:TriggerRefinement):TriggerRefinement {
  return (obj || new TriggerRefinement()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTriggerRefinement(bb:flatbuffers.ByteBuffer, obj?:TriggerRefinement):TriggerRefinement {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TriggerRefinement()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

runId():string|null
runId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
runId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

role():SessionDeviceRole {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : SessionDeviceRole.UNASSIGNED;
}

provisionalHostSensorNanos():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

refinedHostSensorNanos():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startTriggerRefinement(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addRunId(builder:flatbuffers.Builder, runIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, runIdOffset, 0);
}

static addRole(builder:flatbuffers.Builder, role:SessionDeviceRole) {
  builder.addFieldInt8(1, role, SessionDeviceRole.UNASSIGNED);
}

static addProvisionalHostSensorNanos(builder:flatbuffers.Builder, provisionalHostSensorNanos:bigint) {
  builder.addFieldInt64(2, provisionalHostSensorNanos, BigInt('0'));
}

static addRefinedHostSensorNanos(builder:flatbuffers.Builder, refinedHostSensorNanos:bigint) {
  builder.addFieldInt64(3, refinedHostSensorNanos, BigInt('0'));
}

static endTriggerRefinement(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTriggerRefinement(builder:flatbuffers.Builder, runIdOffset:flatbuffers.Offset, role:SessionDeviceRole, provisionalHostSensorNanos:bigint, refinedHostSensorNanos:bigint):flatbuffers.Offset {
  TriggerRefinement.startTriggerRefinement(builder);
  TriggerRefinement.addRunId(builder, runIdOffset);
  TriggerRefinement.addRole(builder, role);
  TriggerRefinement.addProvisionalHostSensorNanos(builder, provisionalHostSensorNanos);
  TriggerRefinement.addRefinedHostSensorNanos(builder, refinedHostSensorNanos);
  return TriggerRefinement.endTriggerRefinement(builder);
}
}
